apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jobservice
  labels:
    app: jobservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jobservice
    spec:
      containers:
      - name: jobservice
        image: vmware/harbor-jobservice:v1.2.0
        env:
          - name: UI_SECRET
            valueFrom:
              secretKeyRef:
                name: ui-secrets
                key: UI_SECRET
          - name: JOBSERVICE_SECRET
            valueFrom:
              secretKeyRef:
                name: jobservice-secrets
                key: JOBSERVICE_SECRET
          - name: LOG_LEVEL
            value: debug
          - name: CONFIG_PATH
            value: /etc/jobservice/app.conf
          - name: GODEBUG
            value: netdns=cgo
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: jobservice-config
          mountPath: /etc/jobservice/app.conf
          subPath: app.conf
        - name: jobservice-secrets
          mountPath: /etc/jobservice/key
          subPath: key
        - name: job-logs
          mountPath: /var/log/jobs
      volumes:
      - name: jobservice-config
        configMap:
          name: jobservice-config
      - name: jobservice-secrets
        secret:
          secretName: jobservice-secrets
          items:
            - key: key
              path: key
      - name: job-logs
        emptyDir: {}
